on:
  push:
    branches: ["main"]

name: Deploy Extension and Package
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build && cd taqwim && npm run build
      - run: xvfb-run -a npm test
      - run: cd taqwim && npm run test

      - name: Publish to VSCode marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com

      - name: Publish to NPM
        run: cd taqwim && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
