on:
  push:
    branches: ["master"]
    
name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm ci
      - run: cd taqwim && npm ci
      - run: npm run build && cd taqwim && npm run build
      - run: xvfb-run -a npm test
      - run: cd taqwim && npm run test
