name: Publish docs
on:
  push:
    branches: ["main"]
    paths: ["docs/**"]

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm ci

      - name: Update rules
        run: cd taqwim && npm run update-rules

      - name: Build docs
        run: npm run docs:build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER}}
          username: ${{ secrets.FTP_ACCOUNT}}
          password: ${{ secrets.FTP_PASSWORD}}
          server-dir: "/taqwim/docs/"
          local-dir: "docs/.vitepress/dist/"
